"""Reusable task families. Each family id maps to one build function and one
ability; the engine never dispatches by question ID."""
from . import local_geometry, force_path, extinction, conformer_design, extent_choice, stereo, crystal, scattering, assembly

FAMILIES = {
    'named_bond_angle': dict(build=local_geometry.build_bond_angle, ability='perception',
                             output='choice+numeric', version=local_geometry.VERSION, module='task_families/local_geometry.py'),
    'backbone_torsion': dict(build=local_geometry.build_backbone_torsion, ability='perception',
                             output='choice+numeric', version=local_geometry.VERSION, module='task_families/local_geometry.py'),
    'extent_choice_v2': dict(build=extent_choice.build, ability='perception',
                             output='choice+numeric', version=extent_choice.VERSION, module='task_families/extent_choice.py'),
    'force_path_derivative': dict(build=force_path.build, ability='inference',
                                  output='choice+numeric', version=force_path.VERSION, module='task_families/force_path.py'),
    'kinematic_extinction': dict(build=extinction.build, ability='inference',
                                 output='choice', version=extinction.VERSION, module='task_families/extinction.py'),
    'conformer_target_selection': dict(build=conformer_design.build, ability='design',
                                       output='choice', version=conformer_design.VERSION, module='task_families/conformer_design.py'),
    'stereo_relationship': dict(build=stereo.build_relationship, ability='perception',
                                output='choice', version=stereo.VERSION, module='task_families/stereo.py'),
    'stereo_property_inference': dict(build=stereo.build_property, ability='inference',
                                      output='choice', version=stereo.VERSION, module='task_families/stereo.py'),
    'stereo_design_selection': dict(build=stereo.build_design, ability='design',
                                    output='choice', version=stereo.VERSION, module='task_families/stereo.py'),
    'named_bond_distance': dict(build=local_geometry.build_bond_distance, ability='perception',
                                output='choice+numeric', version=local_geometry.VERSION, module='task_families/local_geometry.py'),
    'coordination_shell': dict(build=crystal.build_coordination, ability='perception',
                               output='choice', version=crystal.VERSION, module='task_families/crystal.py'),
    'first_diffraction_peak': dict(build=crystal.build_first_peak, ability='inference',
                                   output='choice+numeric', version=crystal.VERSION, module='task_families/crystal.py'),
    'fret_efficiency': dict(build=scattering.build_fret, ability='inference',
                            output='choice+numeric', version=scattering.VERSION, module='task_families/scattering.py'),
    'guinier_intensity': dict(build=scattering.build_guinier, ability='inference',
                              output='choice+numeric', version=scattering.VERSION, module='task_families/scattering.py'),
    'assembly_extent': dict(build=assembly.build_extent, ability='perception',
                            output='choice+numeric', version=assembly.VERSION, module='task_families/assembly.py'),
    'assembly_rg': dict(build=assembly.build_rg, ability='perception',
                        output='choice+numeric', version=assembly.VERSION, module='task_families/assembly.py'),
    'capsid_architecture': dict(build=assembly.build_capsid, ability='inference',
                                output='choice+numeric', version=assembly.VERSION, module='task_families/assembly.py'),
}
